Fixes signing prepared message and test vectors with wrong salt.
cfrg/draft-irtf-cfrg-blind-signatures pull request #209
Opened 2023-07-06 19:29 UTC by armfazh

Fixes signing prepared message and test vectors with wrong salt.

2023-07-06 19:32 UTC, chris-wood commented on draft-irtf-cfrg-rsa-blind-signatures.md
> +## new deterministic test vector Test Vector
This test vector shouldn't be included.

2023-07-06 19:32 UTC, chris-wood commented on draft-irtf-cfrg-rsa-blind-signatures.md
> +## new probabilistic test vector Test Vector
This test vector shouldn't be included.

2023-07-06 19:32 UTC, chris-wood commented on draft-irtf-cfrg-rsa-blind-signatures.md
> +## deterministic Test Vector
This test vector shouldn't be included.

2023-07-06 19:34 UTC, chris-wood requested changes
Nice! We need to drop two test vectors, but otherwise this is good.

2023-07-06 19:45 UTC, armfazh commented on draft-irtf-cfrg-rsa-blind-signatures.md
> +## deterministic Test Vector
done

2023-07-10 22:29 UTC, chris-wood approved these changes

2023-07-10 22:30 UTC, merged